# permissions for end users to edit targets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: target-editor-role
rules:
- apiGroups:
  - tgtd.unstable.cloud
  resources:
  - targets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tgtd.unstable.cloud
  resources:
  - targets/status
  verbs:
  - get
